name = "traktgrambot"
main = "src/index.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]
account_id = "58311076771fec821305824887d5da1f"

# KV namespace bindings for OAuth state and user session storage
[[kv_namespaces]]
binding = "STORE"
id = "adb1f4fb9dcf41ff89eac2d8a73881ec"
preview_id = "5d5603f7d4144f73811201ae8e7dd525"

# Production environment
[env.production]
name = "traktgrambot"
account_id = "58311076771fec821305824887d5da1f"

[[env.production.kv_namespaces]]
binding = "STORE"
id = "adb1f4fb9dcf41ff89eac2d8a73881ec"